version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'lab8_spring'
      MYSQL_PASSWORD: 'random-pass'
      MYSQL_ROOT_PASSWORD: 'random-pass'
    ports:
      - '3307:3306'
    expose:
      - '3307'